Update xdp-xrt-build.yml

diff --git a/.github/workflows/xdp-xrt-build.yml b/.github/workflows/xdp-xrt-build.yml
--- a/.github/workflows/xdp-xrt-build.yml
+++ b/.github/workflows/xdp-xrt-build.yml
@@ -16,8 +16,16 @@ jobs:
     if: |
       github.event_name == 'push' || 
       contains(github.event.pull_request.labels.*.name, 'build-edge') 
-    runs-on: [self-hosted, petalinux]
-    # ubuntu-latest or ubuntu-20.04 or something else?
+    runs-on: ubuntu-latest # or ubuntu-20.04 or something else?
+    container:
+      image: xcoacasharbor.amd.com/aie-ipu-build-docker-local/flexml-rt-lnx:u24.11262025
+      volumes:
+        - /proj:/proj
+        - /build:/build
+        - /group:/group
+        - /tool:/tool
+        - /tools:/tools
+        - /wrk:/wrk
     timeout-minutes: 90
     
     steps:
@@ -46,9 +54,14 @@ jobs:
         # Copy PR changes to XDP location
         cp -r xdp-pr/* $XDP_PATH/
         
-        # Show what changed
-        cd $XDP_PATH
-        git diff --stat
+        ## Show what changed
+        #cd $XDP_PATH
+        #ls -la
+
+    - name: Check PetaLinux Access
+      run: |
+        echo "Checking PetaLinux installation..."
+        ls -la /proj/petalinux/ || echo "PetaLinux not found at /proj/petalinux"
         
     - name: Setup Build Environment Using XRT Scripts
       run: |
